# Generated by Django 5.2.15 on 2026-06-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('moneda_local', models.CharField(help_text='Código ISO de 3 letras, ej: EUR, USD, MXN', max_length=3, verbose_name='Moneda local')),
                ('costo_vida_diario', models.DecimalField(decimal_places=2, help_text='Costo estimado por día para una persona', max_digits=10, verbose_name='Costo de vida diario')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['costo_vida_diario'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('dias_estimados', models.PositiveIntegerField(verbose_name='Días estimados')),
                ('moneda_usuario', models.CharField(max_length=3, verbose_name='Moneda del usuario')),
                ('tasa_cambio_usada', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tasa de cambio usada')),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo total estimado')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='planificador.destino', verbose_name='Destino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto de viaje',
                'verbose_name_plural': 'Presupuestos de viaje',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('VUELO', 'Vuelo'), ('ALOJAMIENTO', 'Alojamiento'), ('COMIDA', 'Comida'), ('TRANSPORTE', 'Transporte'), ('OCIO', 'Ocio/Entretenimiento'), ('OTROS', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo estimado')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_gasto', to='planificador.presupuestoviaje', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Item de gasto',
                'verbose_name_plural': 'Items de gasto',
            },
        ),
    ]
